HEADERS_DIR = include

HEADERS = $(HEADERS_DIR)/log_format.h \
          $(HEADERS_DIR)/xlog_format.h \
          $(HEADERS_DIR)/log_xml_format.h \
          $(HEADERS_DIR)/log_output.h \
          $(HEADERS_DIR)/log_console_output.h \
          $(HEADERS_DIR)/log_file_output.h \
          $(HEADERS_DIR)/logger.h \
          $(HEADERS_DIR)/xconfig.h \
          $(HEADERS_DIR)/log_fac.h \
          $(HEADERS_DIR)/test_class.h

SOURCES = xlog_format.cpp \
          log_xml_format.cpp \
          log_console_output.cpp \
          log_file_output.cpp \
          logger.cpp \
          xconfig.cpp \
          log_fac.cpp \
          test_class.cpp \
          main.cpp

include ../../common-m.mk
